templateproject/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns=[
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other')
]

templateproject/templateproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'basicapp/', include('basicapp.urls'))
]

templateproject/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number':100}
    return render(request,'basicapp/index.html', context=context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative.html')

templateproject/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li> <a class="navbar-link" href="{%url 'admin:index'%}">Admin</a> </li>
          <li> <a class="navbar-link" href="{%url 'basicapp:other'%}">Other</a> </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templateproject/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block%}
    <h1>Welcome to Index</h1>
    <h2>This is the index inheriting from base</h2>
    {{text|cut:"hello"}}
    {{number|add:"2"}}
  {% endblock %}

templateproject/templates/basicapp/other.html
<!DOCTYPE html>
{% extends 'basicapp/base.html'%}

{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance.</h2>
{%endblock%}

templateproject/templates/basicapp/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url.</h1>
    <a href="{%url 'basicapp:other'%}">The Other Page</a>
    <a href="{%url 'admin:index' %}">Admin</a>
    <a href="{%url 'index' %}">Index</a>
  </body>
</html>